version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: sentry
      POSTGRES_USER: sentry  
      POSTGRES_PASSWORD: sentry
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sentry"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data: